dbt_bigquery_data_pipeline:
  outputs:
    dev:
      dataset: dbt_project
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: service-account
      priority: interactive
      project: ecstatic-night-457507-v7
      threads: 4
      type: bigquery
      # For service account auth:
      keyfile: /usr/local/airflow/dbt/service_account.json
  target: dev

